//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ATT.Infrastructure.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int ID { get; set; }
        public System.Guid EUID { get; set; }
        public string Name { get; set; }
        public int TypeID { get; set; }
        public string PasswordHash { get; set; }
    
        public virtual AccountType AccountType { get; set; }
    }
}
